# Generated by Django 3.2.3 on 2021-09-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroApp', '0002_astrologerdetails_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologerdetails',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='astrologerdetails',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='astrologerdetails',
            name='rating',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrologerdetails',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
