# Generated by Django 3.2.3 on 2021-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroApp', '0003_auto_20210927_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologerdetails',
            name='additionalPerMinuteCharges',
            field=models.FloatField(default=5.0, max_length=200),
            preserve_default=False,
        ),
    ]
